# Generated by Django 3.0.2 on 2020-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200209_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unredcount',
            field=models.IntegerField(default=0),
        ),
    ]
