# Generated by Django 3.0.3 on 2020-02-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_unredcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
